### ISSUE TITLE
100% Code coverage

### ISSUE THREAD

**Issue by andreacivita** [andreacivita/Laravel-ApiCrudGenerator#19]
Code-coverage has not 100% of lines tested.

**Comment by lordmen99** [comment]
i got some error when update using latest version :

{
    "success": false,
    "message": "syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM)",
    "code": 0
}

how fix this

**Comment by andreacivita** [comment]
Please, follow default schema of bug reporting.
You can find template here: 
[https://github.com/andreacivita/Laravel-ApiCrudGenerator/blob/master/.github/ISSUE_TEMPLATE/bug_report.md](https://github.com/andreacivita/Laravel-ApiCrudGenerator/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
