### ISSUE TITLE
Method all( ) is not working

### ISSUE THREAD

**Issue by andreacivita** [andreacivita/Laravel-ApiCrudGenerator#22]
**Describe the bug**
Method all is using CRUD table and not working for other db

**To Reproduce**
1. Use db not named 'crud'
2. php artisan make:crud --all
4. See error "not finding tables_in_crud"

**Comment by andreacivita** [comment]
Fixed

**Comment by softwarefan** [comment]
Executing command:  php artisan make:crud --all  gives  me this error:

  TypeError 
 Argument 2 passed to AndreaCivita\ApiCrudGenerator\Core\Generators\RouteGenerator::setData() must be of the type bool, null given, called in D:\wamp64\www\test\vendor\andreacivita\api-crud-generator\src\Commands\ApiCrudGenerator.php on line 249
