### ISSUE TITLE
Missing namespace in Factory

### ISSUE THREAD

**Issue by andreacivita** [andreacivita/Laravel-ApiCrudGenerator#30]
**Describe the bug**
Namespace in factory stub is missing, and should be `namespace Database\Factories`. It will cause an error using this factory.

**To Reproduce**
1. ```php artisan make:crud --interactive```
2. Fill with data...
3. Factory file in `database/factories/FooFactory.php` has no namespace

**Comment by maxvrdev** [comment]
I submitted a PR for this issue.
