### ISSUE TITLE
how make secure?

### ISSUE THREAD

**Issue by lordmen99** [andreacivita/Laravel-ApiCrudGenerator#9]
Dear bro, ur code generator api is good. i have been setup in my classified script, its working. but how make secure example if want access api must have login user (email & pass) combine with expired token

**Comment by andreacivita** [comment]
Hi man! 
First of all, i'm valuating a pull request from bastiani, so stay tuned for further information :)

The answer to your question is Laravel Passport.
It allows secure access to API (you just need to add passport Middleware to your API) and works with tokens.

Please see Passport tutorial for securing your API :)

**Comment by lordmen99** [comment]
laravel passport can connected with my user table from my classified script?

**Comment by andreacivita** [comment]
Yes, passport will set a token for your logged user and give access to API only if token is correct. 
It's a bit more complicated, but it works great :)

**Comment by lordmen99** [comment]
can u add too passport to this code, so when make "php artisan make:crud nametable" its will create auth passport too in controller

**Comment by andreacivita** [comment]
I will think about it, but i do not think it will happen. I will let this feature open :)

**Comment by andreacivita** [comment]
Happy news! 
Passport support will come with next release :)

**Comment by lordmen99** [comment]
when?

**Comment by andreacivita** [comment]
You can stay tuned for updates here: 
https://github.com/andreacivita/Laravel-ApiCrudGenerator/tree/passport-integration
Or waiting for a new release.
If you have further suggestion, please open issue or fork this repo and submit a pull request :)

**Comment by lordmen99** [comment]
passport integration have done?

**Comment by andreacivita** [comment]
I'ts almost done, now it has been moved in dev-branch, so you'll need to stay tuned while some minor fixes are applied. 
Today or tomorrow you'll find a new release :)

**Comment by andreacivita** [comment]
Partial-enhancement added with new release (0.4.0)

**Comment by lordmen99** [comment]
have added for passport? i see in command still not appears

**Comment by andreacivita** [comment]
you should add --passport and it works
Like
`php artisan make:crud --all --passport`
